import { LandingNavigation } from './landing-navigation';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, ChartNoAxesCombined, Database, FlaskConical, MessagesSquare, ShieldCheck, Sparkles, Star } from 'lucide-react';
import { Brand } from './brand';
import { BrandSky } from './brand-sky';

const features = [
  { icon: ChartNoAxesCombined, number: '01', title: 'Understand the movement.', text: 'Explore completed-session prices, moving averages and company financials. See where the evidence comes from.', tag: 'Stock research', href: '/stock-analysis' },
  { icon: Sparkles, number: '02', title: 'Put the signals in context.', text: 'Read an AI perspective grounded in the available data, with risks and missing information alongside the outlook.', tag: 'AI insight', href: '/stock-analysis' },
  { icon: MessagesSquare, number: '03', title: 'Ask your next question.', text: 'Talk through cash flow, budgeting and financial concepts with your AI CFO. Return to your saved conversations.', tag: 'AI CFO', href: '/cfo' },
];

function ResearchPreview() {
  return <div className="relative mx-auto w-full max-w-[440px]" aria-label="Illustration of the research workflow, not live market data">
    <div className="absolute -inset-8 rounded-full bg-blue-500/10 blur-3xl" />
    <div className="preview-float relative overflow-hidden rounded-3xl border border-blue-300/25 bg-[#0a1b2c]/90 shadow-2xl shadow-black/30">
      <div className="flex items-center justify-between gap-3 border-b border-white/10 px-6 py-4"><span className="flex items-center gap-2 text-[10px] text-slate-300"><span className="h-2 w-2 shrink-0 rounded-full bg-cyan-300" />YOUR RESEARCH WORKSPACE</span><span className="text-[9px] text-slate-400">ILLUSTRATION</span></div>
      <div className="p-5">
        <div className="flex items-center gap-3"><div className="rounded-xl bg-blue-400/10 p-3 text-blue-300"><ChartNoAxesCombined size={24} /></div><div><p className="text-xl font-semibold">A bigger picture.</p><p className="mt-1 text-xs text-muted-foreground">From daily prices to informed questions</p></div></div>
        <div className="relative my-4 rounded-xl border border-white/5 bg-[#071522] px-3 pt-5">
          <svg viewBox="0 0 460 180" className="w-full" aria-hidden="true"><defs><linearGradient id="preview-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#28dce3" stopOpacity=".22" /><stop offset="1" stopColor="#28dce3" stopOpacity="0" /></linearGradient></defs>{[30,75,120,165].map(y => <path key={y} d={`M0 ${y}H460`} stroke="#264052" strokeDasharray="3 6" />)}<path d="M0 143L25 136L48 147L72 111L96 118L120 98L144 116L168 87L192 99L216 68L240 78L264 62L288 89L312 49L336 62L360 38L384 51L408 27L432 39L460 17V180H0Z" fill="url(#preview-fill)" /><path d="M0 143L25 136L48 147L72 111L96 118L120 98L144 116L168 87L192 99L216 68L240 78L264 62L288 89L312 49L336 62L360 38L384 51L408 27L432 39L460 17" className="preview-line" pathLength="1" fill="none" stroke="#58dce6" strokeWidth="2.5" /><circle className="preview-beacon" cx="460" cy="17" r="5" fill="#9afff6"/><circle className="preview-beacon preview-beacon-delayed" cx="264" cy="62" r="4" fill="#9afff6"/></svg>
          <div className="flex justify-between py-3 text-[10px] uppercase tracking-widest text-slate-400"><span>Evidence</span><span>Perspective</span></div>
        </div>
        <div className="grid grid-cols-3 gap-3">{[['Prices','See the history'],['Signals','Find the context'],['Risks','Know the limits']].map(([title,caption])=><div key={title} className="rounded-xl border border-white/10 bg-white/[.02] px-3 py-3"><p className="text-sm font-medium text-white">{title}</p><p className="mt-2 text-[11px] leading-5 text-muted-foreground">{caption}</p></div>)}</div>
        <div className="mt-4 flex items-start gap-3 rounded-xl border border-blue-400/20 bg-blue-500/10 p-4"><Sparkles size={19} className="mt-0.5 shrink-0 text-blue-300"/><p className="text-xs leading-6 text-slate-300">An AI perspective, with the evidence and uncertainty in view.</p></div>
      </div>
    </div>
  </div>;
}

export function LandingPage() {
  return <div className="terminal-shell min-h-dvh text-foreground">
    <LandingNavigation/>
    <main id="main-content">
      <section className="relative isolate overflow-hidden border-b border-white/10"><BrandSky/>
        <div className="landing-hero relative mx-auto grid max-w-6xl items-center gap-10 px-6 py-10 lg:grid-cols-2 lg:gap-10 lg:px-8">
          <div className="text-center"><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/5 px-4 py-2 text-[11px] font-medium tracking-[.16em] text-cyan-200"><Sparkles size={13}/> FINANCIAL CLARITY WITH AI</p><h1 className="mx-auto max-w-2xl text-4xl font-semibold leading-[1.08] tracking-[-.045em] sm:text-5xl">Less noise.<br/>More <span className="bg-gradient-to-r from-blue-300 to-cyan-300 bg-clip-text text-transparent">perspective.</span></h1><p className="mx-auto mt-5 max-w-lg text-base leading-7 text-muted-foreground">Make sense of the market. Bring stock research, AI insights and your financial questions into one clear workspace.</p><div className="landing-actions mt-6 flex flex-wrap justify-center gap-3"><Link href="/signup" className="app-button !min-h-12 !px-6">Create your account <ArrowRight size={17}/></Link><Link href="/stock-analysis" className="app-button-secondary !min-h-12 !px-6">Explore the workspace</Link></div><p className="mt-5 text-xs leading-6 text-slate-400">Built for research and learning. No brokerage connection required.</p></div><ResearchPreview/>
        </div>
      </section>
      <div className="mx-auto grid max-w-6xl gap-5 border-b border-white/10 px-6 py-8 text-sm text-muted-foreground sm:grid-cols-3 lg:px-10">{[[Database,'Visible data sources'],[ShieldCheck,'Risks alongside the outlook'],[Star,'A watchlist that stays with you']].map(([Icon,text])=>{const Glyph=Icon as typeof Database;return <p key={String(text)} className="flex items-center gap-3"><Glyph size={18} className="text-cyan-300"/>{String(text)}</p>;})}</div>
      <section id="how-it-works" className="mx-auto max-w-6xl scroll-mt-8 px-6 py-20 lg:px-10 lg:py-24"><p className="app-eyebrow">A clearer way to research</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">From a ticker to a better question.</h2><div className="mt-10 grid gap-5 lg:grid-cols-3">{features.map(({icon:Icon,...item})=><Link key={item.number} href={item.href} className="group rounded-2xl border border-border bg-[#0b1b2b] p-7 transition-colors hover:border-blue-400/60"><div className="flex items-center justify-between"><Icon size={26} className="text-blue-300"/><span className="text-xs tracking-widest text-slate-500">{item.number}</span></div><p className="mt-9 text-xs font-medium text-cyan-300">{item.tag}</p><h3 className="mt-3 text-xl font-semibold leading-7">{item.title}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{item.text}</p><ArrowUpRight size={20} className="mt-6 text-blue-300 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></Link>)}</div></section>
      <section className="mx-auto grid max-w-6xl gap-10 px-6 pb-20 lg:grid-cols-2 lg:px-10"><div className="insight-panel p-8 sm:p-10"><FlaskConical className="text-cyan-300" size={27}/><p className="app-eyebrow mt-7">The model lab</p><h2 className="mt-4 text-3xl font-semibold tracking-tight">Test the idea.<br/>Respect the uncertainty.</h2><p className="mt-5 text-sm leading-7 text-muted-foreground">Explore experimental forecasts with historical evaluation and simple baselines. When a model fails its quality checks, we show that result instead of a prediction.</p><Link href="/stock-analysis" className="mt-7 inline-flex min-h-11 items-center gap-2 text-sm font-medium text-blue-300">Explore stock research <ArrowRight size={16}/></Link></div><div className="py-4 md:px-6"><p className="app-eyebrow">Before you begin</p><h2 className="mt-4 text-3xl font-semibold tracking-tight">Clarity includes the limitations.</h2><div className="mt-6 space-y-3">{[['Is this live trading data?','No. Price history uses completed trading sessions. Sources, timestamps and any missing inputs are shown in the workspace.'],['What does the AI provide?','An interpretation of the available evidence, not a guaranteed outcome or personalized investment advice. AI can make mistakes.'],['What do I need an account for?','Sign in to request stock analysis, save a watchlist and keep AI CFO conversations. Feature usage limits and data availability apply.']].map(([q,a])=><details key={q} className="app-details"><summary>{q}</summary><p className="px-5 py-4 text-sm leading-7 text-muted-foreground">{a}</p></details>)}</div></div></section>
      <section className="border-y border-blue-300/15 bg-blue-500/5 px-6 py-16 text-center"><p className="app-eyebrow">Your next chapter</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Start with curiosity.<br/>Build your perspective.</h2><Link href="/signup" className="app-button mt-8 !px-7">Get started with Zeitgeist <ArrowRight size={17}/></Link></section>
    </main><footer className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-6 px-6 py-9 text-xs leading-6 text-muted-foreground lg:px-10"><Brand/><p>Educational research. Not licensed financial advice.<br/>Market data may be delayed. Verify before making decisions.</p><div className="flex gap-5"><Link href="/login">Sign in</Link><Link href="/signup">Create account</Link></div></footer>
  </div>;
}
