"use client";
import {useState} from 'react';
import {pairedComparison,type Calibration} from '@/lib/model-comparison';
import type {LedgerRecord} from '@/lib/forward-results';
export function ModelComparison({records}:{records:LedgerRecord[]}){
 const choices=[...new Set(records.map(r=>`${r.model_id}|${r.model_version}`))];
 const [selection,setSelection]=useState<string[]|null>(null);
 const selected=selection??choices.slice(0,3),paired=pairedComparison(records,selected);
 return <details className="mt-6 rounded-xl border border-border p-4"><summary className="cursor-pointer font-medium">Compare on matching evidence</summary><p className="mt-3 text-xs leading-6 text-muted-foreground">Only completed, published predictions with the same stock, origin, target, input fingerprint and observed return are compared. Select two or more models.</p><div className="mt-3 flex flex-wrap gap-3">{choices.map(k=><label key={k} className="flex max-w-full items-center gap-2 text-xs"><input type="checkbox" checked={selected.includes(k)} onChange={e=>setSelection(e.target.checked?[...selected,k]:selected.filter(m=>m!==k))}/><span className="break-all">{k.replace('|',' · ')}</span></label>)}</div><p role="status" className="mt-4 text-sm text-primary">{paired.samples} matching completed samples</p>{paired.scorecard.length>0&&<div className="mt-3 overflow-x-auto"><table className="w-full min-w-[480px] text-left text-sm"><thead><tr><th>Model</th><th>MAE (pp)</th><th>Direction</th></tr></thead><tbody>{paired.scorecard.map(r=><tr className="border-t border-border" key={r.model+r.version}><td className="py-3">{r.model}</td><td>{r.mae?.toFixed(2)??'—'}</td><td>{r.direction_hit_pct===null?'—':`${r.direction_hit_pct.toFixed(1)}%`}</td></tr>)}</tbody></table></div>}<ul className="mt-3 text-xs leading-6 text-muted-foreground">{paired.coverage.map(r=><li key={r.model}>{r.model.split('|')[0]}: {r.published}/{r.recorded} published · {r.completed} completed</li>)}</ul><p className="mt-3 text-xs text-muted-foreground">No automatic model promotion. Overlapping windows and small samples remain a limitation.</p></details>;
}
export function IntervalSummary({records}:{records:(LedgerRecord & {interval?:Calibration|null})[]}){
 const completed=records.filter(r=>r.prospective&&r.interval?.state==='ready'&&r.checks?.state==='settled'&&r.checks.outcome);
 const hits=completed.filter(r=>r.checks!.outcome!.actual_return_pct>=r.interval!.lower_return_pct!&&r.checks!.outcome!.actual_return_pct<=r.interval!.upper_return_pct!).length;
 return <div className="mt-5 border-t border-border pt-4 text-sm"><h4 className="font-medium">Observed interval coverage</h4><p className="mt-2 text-muted-foreground">{completed.length?`${hits}/${completed.length} outcomes inside their frozen 80% nominal bands (${(hits/completed.length*100).toFixed(1)}%).`:'No completed calibrated intervals yet.'}</p><p className="mt-2 text-xs leading-6 text-muted-foreground">A band requires at least 30 earlier, completed, non-overlapping windows for the same model version. It uses past errors across stocks and is frozen when the prediction is saved. Coverage is measured after maturity; 80% is a target, not a guarantee. Older predictions are not backfilled.</p></div>;
}
