"use client";
import { AnalysisProgress } from './analysis-progress';
import Link from 'next/link';
import { useState } from 'react';
import { Sparkles, ArrowUpRight, ArrowDownRight, ChevronRight, ShieldAlert, ChartNoAxesCombined, Database, LoaderCircle, RotateCcw, Search, Info } from 'lucide-react';
import type { StockAnalysis } from '@/types/stock';
import type { MarketResult } from '@/lib/stock-flow';
import StockPriceDisplay from './stock-price-display';
import dynamic from 'next/dynamic';
const StockChart = dynamic(() => import('./stock-chart'), { ssr: false, loading: () => <p role="status" className="flex h-96 items-center justify-center text-sm text-muted-foreground">Preparing the price chart…</p> });
import AnalysisDisplay from './analysis-display';
import AnalysisUnavailable from './analysis-unavailable';
import { StockEvidence } from './stock-evidence';
import { StockFinancials } from './stock-financials';
import { StockNews } from './stock-news';
import { ForecastLab } from './forecast-lab';
import { cn } from '@/lib/utils';
interface Props { market: MarketResult|null; analysis:StockAnalysis|null; fetchingStock:boolean; fetchingAnalysis:boolean; error:string|null; analysisError:string|null; ticker:string; cached:boolean; needsLogin:boolean; onSearch:(ticker:string)=>void; onRetry:()=>void; onReset:()=>void }
export function ResearchDashboard({market,analysis,fetchingStock,fetchingAnalysis,error,analysisError,ticker,cached,needsLogin,onSearch,onRetry,onReset}:Props) {
  const [section,setSection]=useState('prices');
  const [sessions,setSessions]=useState(0);
  const evidence=market?.evidence ?? analysis?.evidence;
  const aiStatus = fetchingStock ? 'Loading prices…' : fetchingAnalysis ? 'Analyzing…' : analysisError ? 'AI unavailable' : market ? 'Analysis pending' : 'Choose a stock';
  const history=sessions ? market?.price_history.slice(-sessions) : market?.price_history;
  return <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_330px] 2xl:grid-cols-[minmax(0,1fr)_360px]">
    <div className="min-w-0 space-y-5">
      {market ? <StockPriceDisplay stockData={market.stock_data} variant="default"/> : <section className="app-panel flex min-h-40 items-center gap-5 p-6 sm:p-7"><span className="hidden h-20 w-20 shrink-0 items-center justify-center rounded-full border border-border bg-primary/5 text-primary sm:flex"><ChartNoAxesCombined size={34}/></span><div><p className="app-eyebrow">Your market workspace</p><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">A clearer view starts here.</h1><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Search a stock to explore its prices, signals and AI perspective.</p></div></section>}
      <section className="app-panel overflow-hidden">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 pt-3"><nav className="research-tabs flex w-full min-w-0 gap-x-4 overflow-x-auto whitespace-nowrap sm:w-auto sm:flex-wrap sm:gap-x-5" aria-label="Research sections">{[['prices','Price history'],['analysis','Key factors'],['financials','Financials'],['forecast','Model lab'],['news','News & sources'],['evidence','Data sources']].map(([key,title])=><button key={key} onClick={()=>setSection(key)} aria-pressed={section===key} className={cn('relative min-h-11 shrink-0 text-xs sm:min-h-14 font-medium sm:text-sm',section===key?'text-white after:absolute after:inset-x-0 after:bottom-0 after:h-[3px] after:rounded-full after:bg-blue-500':'text-muted-foreground hover:text-white')}>{title}</button>)}</nav>{section==='prices' && market && <div className="mb-2 flex rounded-xl border border-border bg-primary/5 p-1">{[[5,'5D'],[10,'10D'],[0,'All']].map(([n,name])=><button key={n} onClick={()=>setSessions(Number(n))} aria-pressed={sessions===n} className={cn('min-h-9 rounded-lg px-3 text-xs',sessions===n?'bg-blue-600 text-white':'text-muted-foreground')}>{name}</button>)}</div>}</div>
        {fetchingStock ? <div role="status" className="flex h-96 flex-col items-center justify-center gap-4 text-muted-foreground"><LoaderCircle size={27} className="animate-spin text-primary"/>Loading {ticker} market data…</div> : error ? <div role="alert" className="flex min-h-80 flex-col items-center justify-center p-8 text-center"><ShieldAlert className="mb-4 text-destructive" size={28}/><h2 className="text-lg font-semibold">We couldn’t load {ticker}</h2><p className="mt-3 max-w-sm text-sm text-muted-foreground">{error}</p>{needsLogin?<Link href="/login?next=%2Fstock-analysis" className="app-button mt-6">Sign in to continue</Link>:<button onClick={()=>onSearch(ticker)} className="app-button-secondary mt-6"><RotateCcw size={15}/>Try again</button>}</div> : section==='prices' && market ? <StockChart data={history ?? []} ticker={market.stock_data.ticker} height={330} className="!rounded-none !border-0 !bg-none !shadow-none"/> : section==='analysis' && analysisError ? <AnalysisUnavailable error={analysisError} ticker={ticker} onRetry={onRetry}/> : section==='analysis' && analysis ? <AnalysisDisplay analysis={analysis} className="!rounded-none !border-0 !bg-none !shadow-none"/> : section==='forecast' && market ? <ForecastLab key={market.snapshot_id} ticker={market.stock_data.ticker}/> : section==='financials' && market ? <StockFinancials financials={market.financials} company={market.company_details} analysis={analysis}/> : section==='news' && market ? <StockNews news={market.news} analysis={analysis} sessionTimestamp={market.stock_data.timestamp}/> : section==='evidence' && evidence ? <StockEvidence evidence={evidence}/> : <div className="p-5 sm:p-7"><div className="mb-6 flex justify-between text-xs text-muted-foreground"><span>Price (USD)</span><span className="flex items-center gap-2"><span className="h-0.5 w-6 bg-blue-500"/>Completed-session closes</span></div><div className="terminal-grid relative flex min-h-72 items-center justify-center sm:min-h-80"><div className="mx-4 max-w-sm rounded-2xl border border-border bg-background/95 p-6 text-center shadow-xl"><Search className="mx-auto mb-3 text-primary" size={24}/><h2 className="font-medium">{market?'Waiting for the AI perspective':'Choose a stock to begin'}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{market?'Your market data is ready. Analysis will appear when generation completes.':'Your price history will appear here after you search. Start with a company you follow.'}</p></div></div><div className="mt-6 flex flex-wrap items-center gap-2"><span className="mr-2 text-xs text-muted-foreground">Explore</span>{['AAPL','MSFT','NVDA','TSLA','GOOGL'].map(symbol=><button disabled={fetchingStock} key={symbol} onClick={()=>onSearch(symbol)} className="rounded-lg border border-border bg-primary/5 px-3 py-2 font-mono text-xs text-primary transition-colors hover:border-primary">{symbol}</button>)}</div></div>}
      </section>
      <div className="grid gap-4 sm:grid-cols-3">
        <section className="app-panel p-5"><p className="text-sm text-muted-foreground">History return</p><div className="mt-3 flex items-center justify-between gap-2"><p className={cn('text-3xl font-semibold tabular-nums',evidence?.return_percent!==null && (evidence?.return_percent ?? 0)<0?'text-rose-300':'data-accent')}>{evidence?.return_percent == null?'—':`${evidence.return_percent>=0?'+':''}${evidence.return_percent.toFixed(2)}%`}</p>{(evidence?.return_percent ?? 0)<0?<ArrowDownRight size={32} className="text-rose-300"/>:<ArrowUpRight size={32} className="text-cyan-400"/>}</div><p className="mt-2 text-xs text-muted-foreground">{evidence?`${evidence.bars} supplied daily bars`:'From supplied closing prices'}</p></section>
        <section className="app-panel p-5"><p className="text-sm text-muted-foreground">Model confidence</p><div className="mt-3 flex items-center justify-between gap-3"><p className={cn("font-semibold tabular-nums",analysis?"text-3xl":"text-base")}>{analysis?`${analysis.confidence_score}%`:aiStatus}</p><svg width="52" height="52" viewBox="0 0 52 52" aria-hidden="true"><circle cx="26" cy="26" r="21" fill="none" stroke="#173354" strokeWidth="7"/>{analysis && <circle cx="26" cy="26" r="21" fill="none" stroke="#447cff" strokeWidth="7" strokeLinecap="round" strokeDasharray={`${(analysis?.confidence_score??0)*1.3195} 132`} transform="rotate(-90 26 26)"/>}</svg></div><p className="mt-2 text-xs text-muted-foreground">{analysis?'Self-assessment, not accuracy':market?'Prices are ready; this value requires AI analysis.':'Search for a stock to begin.'}</p></section>
        <section className="app-panel p-5"><p className="text-sm text-muted-foreground">Model outlook</p><p className="data-accent mt-4 text-2xl font-semibold capitalize">{analysis?analysis.recommendation.replaceAll('_',' ').toLowerCase():aiStatus}</p><p className="mt-3 text-xs text-muted-foreground">{analysis?`${analysis.risk_level.toLowerCase()} risk assessment`:analysisError?'Prices available · See the AI status panel':market?'Prices available · AI result pending':'Search for a stock to begin.'}</p></section>
      </div>
      {market && <div className="flex flex-wrap items-center justify-between gap-3 text-xs text-muted-foreground"><span>{cached?'Saved analysis reused.':'Completed-session market data.'}</span><div className="flex gap-3"><button onClick={()=>onSearch(ticker)} className="inline-flex min-h-10 items-center gap-2 hover:text-white"><RotateCcw size={13}/>Refresh prices</button><button className="min-h-10 hover:text-white" onClick={onReset}>New search</button></div></div>}
      <div id="data-evidence" className="scroll-mt-36">{evidence && section!=='evidence' && <StockEvidence evidence={evidence}/>}<details className="app-panel mt-4 p-5"><summary className="cursor-pointer text-sm font-medium">About our data sources</summary><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Daily price source: {evidence?.source ?? "shown after selecting a stock"}. Company information is available when supplied by the selected provider. Moving averages and historical returns are calculated from supplied daily bars. AI interpretation is generated separately. Related news is provided separately by Polygon.io when available, with publication times and original links under News & sources. Income statements, balance sheets and cash flows are shown under Financials when available, with separate reporting periods. Live quotes and filing dates are not supplied.</p></details></div>
    </div>
    <aside className="insight-panel flex min-h-[580px] flex-col p-6 xl:sticky xl:top-28" aria-label="AI insight">
      <header className="flex items-center gap-3"><Sparkles className="text-blue-400" size={29}/><h2 className="text-xl font-semibold">AI Insight</h2><span className="rounded-lg bg-blue-500/20 px-2 py-1 text-[10px] font-medium text-primary">AI</span></header>
      {analysis && evidence && evidence.bars < 2 && !fetchingAnalysis && <div role="status" className="mt-5 rounded-xl border border-amber-400/25 bg-amber-400/5 p-4"><p className="text-sm font-medium text-amber-200">Historical prices are missing</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">This analysis has too few daily bars to assess a trend. Refresh market data to try again with historical prices.</p><button disabled={fetchingStock} onClick={()=>onSearch(ticker)} className="mt-3 inline-flex min-h-10 items-center gap-2 text-sm text-primary disabled:opacity-50"><RotateCcw size={14}/>{fetchingStock?'Refreshing…':'Refresh market data'}</button></div>}
      {analysisError && !fetchingAnalysis ? <div className="mt-6"><AnalysisUnavailable error={analysisError} ticker={ticker} onRetry={onRetry}/></div> : fetchingAnalysis ? <AnalysisProgress key={market?.snapshot_id}/> : analysis ? <><h3 className="mt-7 text-xl font-semibold leading-relaxed">{analysis.company_name}: {analysis.technical_analysis.trend.toLowerCase()} technical outlook</h3><p className="mt-4 whitespace-pre-line text-sm leading-7 text-muted-foreground">{analysis.summary}</p><div className="my-6 rounded-xl border border-border bg-primary/5 p-4"><p className="text-xs text-muted-foreground">Short-term model target · 1–3 months</p><p className="mt-3 text-2xl font-semibold text-cyan-300">{analysis.price_targets.short_term==null?'Not estimated':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(analysis.price_targets.short_term)}</p><p className="mt-2 text-xs text-muted-foreground">{analysis.price_targets.short_term==null?'The available evidence does not support a price target.':'A scenario, not a guaranteed outcome.'}</p></div><section className="border-t border-border pt-5"><h3 className="flex items-center gap-2 font-medium text-rose-400"><ShieldAlert size={20}/>Key risks</h3><ul className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">{analysis.risk_factors.slice(0,3).map((risk,i)=><li className="flex gap-2" key={i}><span className="text-rose-400">•</span>{risk}</li>)}</ul></section><button className="mt-5 min-h-10 text-left text-sm text-primary hover:underline" onClick={()=>setSection('analysis')}>View full analysis →</button></> : <><h3 className="mt-7 text-xl font-semibold leading-relaxed">Turn market data into a clearer perspective.</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">Select a stock to explore its momentum, potential risks and the evidence behind the AI interpretation.</p><div className="my-7 rounded-xl border border-border bg-primary/5 p-5"><p className="text-xs text-muted-foreground">Analysis status</p><p className="mt-3 text-lg font-medium text-cyan-300">{market?'Market data received':'Ready when you are'}</p></div><div className="space-y-5 text-sm text-muted-foreground">{[[ChartNoAxesCombined,'Calculated technical signals'],[Database,'Visible sources and limitations'],[ShieldAlert,'Risks alongside the outlook']].map(([Icon,text])=>{const Glyph=Icon as typeof Database;return <p key={String(text)} className="flex items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-blue-500/15 text-primary"><Glyph size={18}/></span>{String(text)}</p>;})}</div></>}
      <div className="mt-auto pt-8"><Link href="/cfo" className="app-button w-full justify-between">Ask an AI question…<ChevronRight size={20}/></Link><p className="mt-4 flex items-start gap-2 text-[11px] leading-relaxed text-muted-foreground"><Info size={14} className="mt-0.5 shrink-0"/>AI can make mistakes. Verify the evidence before acting.</p></div>
    </aside>
  </div>;
}
