import type { StockSnapshot } from '@/lib/stock-evidence';

export function StockEvidence({ evidence }: { evidence: StockSnapshot['evidence'] }) {
  const number = (value: number | null) => value === null ? 'Unavailable' : value.toFixed(2);
  return (
    <section className="rounded-2xl border border-border bg-card p-5 sm:p-7 space-y-4" aria-label="Analysis data sources">
      <h2 className="font-semibold">Data behind this analysis</h2>
      <p className="text-sm text-muted-foreground">Source: {evidence.source} · Completed session: {evidence.session_date} (ET)</p>
      <p className="text-sm text-muted-foreground">History: {evidence.history_start ?? 'unavailable'} to {evidence.history_end ?? 'unavailable'} · {evidence.bars} completed daily bars</p>
      <dl className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-sm [&>div]:rounded-xl [&>div]:bg-background [&>div]:p-4 [&_dt]:text-xs [&_dt]:text-muted-foreground [&_dd]:mt-2 [&_dd]:text-xl [&_dd]:font-medium [&_dd]:tabular-nums">
        <div><dt>5-session average close</dt><dd>{number(evidence.sma5)}</dd></div>
        <div><dt>20-session average close</dt><dd>{number(evidence.sma20)}</dd></div>
        <div><dt>Return over supplied history</dt><dd>{evidence.return_percent === null ? 'Unavailable' : number(evidence.return_percent) + '%'}</dd></div>
      </dl>
      <p className="text-xs text-muted-foreground">These indicators are calculated from the daily closes, not generated by AI. Unavailable inputs: {evidence.missing.join(', ')}.</p>
      <p className="break-words text-xs text-muted-foreground">Retrieved: {evidence.fetched_at}</p>
    </section>
  );
}
