"use client";
import { useMemo, useState, useId, type ReactNode } from 'react';
import { Area, AreaChart, Line, LineChart, ComposedChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { cn } from '@/lib/utils';
import type { StockPriceData, ChartConfig } from '@/types/stock';
interface Props { toolbar?: ReactNode; compact?: boolean; data: StockPriceData[]; ticker: string; className?: string; config?: Partial<ChartConfig>; showVolume?: boolean; showControls?: boolean; height?: number }
const money = (n: number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const compact = (n: number) => new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n);
function PriceTooltip({ active, payload }: { active?: boolean; payload?: Array<{ payload: StockPriceData }> }) {
  if (!active || !payload?.length) return null;
  const bar = payload[0].payload;
  return <div className="rounded-xl border border-border bg-popover p-4 shadow-xl"><p className="mb-3 text-xs font-medium text-muted-foreground">{bar.date}</p><dl className="space-y-2">{[['Close',money(bar.close)],['Open',money(bar.open)],['High',money(bar.high)],['Low',money(bar.low)],['Volume',compact(bar.volume)]].map(([key,value])=><div key={key} className="flex min-w-40 justify-between gap-6 text-xs"><dt className="text-muted-foreground">{key}</dt><dd className="font-medium tabular-nums">{value}</dd></div>)}</dl></div>;
}
export function StockChart({data,ticker,className,config,showVolume=false,showControls=true,height=360,compact:compactView=false,toolbar}: Props) {
  const [type,setType] = useState(config?.chart_type === 'line' ? 'line' : 'area');
  const [volume,setVolume] = useState(config?.show_volume ?? showVolume);
  const gradient = useId().replaceAll(':','');
  const bars = useMemo(()=>[...data].sort((a,b)=>a.timestamp-b.timestamp),[data]);
  const axes = <><CartesianGrid vertical={false} stroke="var(--border)" strokeOpacity={0.45} strokeDasharray="3 6"/><XAxis dataKey="date" tickLine={false} axisLine={false} minTickGap={35} tick={{fill:'var(--muted-foreground)',fontSize:11}} tickFormatter={value=>String(value).slice(5)}/><YAxis yAxisId="price" orientation="right" domain={['auto','auto']} width={65} tickLine={false} axisLine={false} tick={{fill:'var(--muted-foreground)',fontSize:11}} tickFormatter={value=>'$'+Number(value).toFixed(0)}/><Tooltip content={<PriceTooltip/>} cursor={{stroke:'var(--muted-foreground)',strokeDasharray:'3 3'}}/></>;
  return <section aria-label={`${ticker} historical prices`} className={cn('app-panel min-w-0',compactView?'p-4':'p-5 sm:p-7',className)}>
    <header className={cn("flex flex-wrap items-center justify-between gap-3",compactView?"mb-3":"mb-6")}><div><h2 className="text-sm font-semibold">{compactView ? "Daily close" : "Price history"}</h2><p className="mt-2 text-xs text-muted-foreground">{bars.length} daily bars · Close in USD{volume ? ' · Volume on left axis' : ''}</p></div>{toolbar}{showControls && <div className="flex flex-wrap items-center gap-2"><div className="flex rounded-xl border border-border bg-background p-1" aria-label="Chart style">{['area','line'].map(value=><button key={value} onClick={()=>setType(value)} aria-pressed={type===value} className={cn('min-h-9 rounded-lg px-3 text-xs font-medium capitalize',type===value?'bg-accent text-foreground':'text-muted-foreground hover:text-foreground')}>{value}</button>)}</div><button onClick={()=>setVolume(!volume)} aria-pressed={volume} className={cn('app-button-secondary text-xs',volume && 'bg-accent')}>Volume</button></div>}</header>
    {bars.length === 0 ? <p className="py-12 text-center text-sm text-muted-foreground">Price history is unavailable for this session.</p> : <><div style={{height}} className="w-full min-w-0" role="img" aria-label={`Daily closing prices for ${ticker}, ${bars[0].date} to ${bars.at(-1)!.date}. Data table below.`}><ResponsiveContainer width="100%" height="100%">{volume ? <ComposedChart data={bars} margin={{top:10,right:0,left:-15,bottom:0}}>{axes}<YAxis yAxisId="volume" width={55} tickLine={false} axisLine={false} tick={{fill:'var(--muted-foreground)',fontSize:10}} tickFormatter={compact}/><Bar yAxisId="volume" dataKey="volume" fill="var(--chart-1)" opacity={0.18}/><Line yAxisId="price" dataKey="close" stroke="var(--chart-1)" strokeWidth={2} dot={false} isAnimationActive={false}/></ComposedChart> : type==='line' ? <LineChart data={bars} margin={{top:10,right:0,left:0,bottom:0}}>{axes}<Line yAxisId="price" dataKey="close" stroke="var(--chart-1)" strokeWidth={2} dot={false} isAnimationActive={false}/></LineChart> : <AreaChart data={bars} margin={{top:10,right:0,left:0,bottom:0}}><defs><linearGradient id={gradient} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--chart-1)" stopOpacity={0.24}/><stop offset="100%" stopColor="var(--chart-1)" stopOpacity={0.01}/></linearGradient></defs>{axes}<Area yAxisId="price" dataKey="close" stroke="var(--chart-1)" strokeWidth={2} fill={`url(#${gradient})`} isAnimationActive={false}/></AreaChart>}</ResponsiveContainer></div><details className="mt-5 border-t border-border pt-4"><summary className="cursor-pointer text-xs text-muted-foreground hover:text-foreground">View daily price data</summary><div className="mt-4 max-h-64 overflow-auto"><table className="w-full text-left text-xs tabular-nums"><caption className="sr-only">{ticker} daily price history</caption><thead className="sticky top-0 bg-card text-muted-foreground"><tr>{['Session','Close','Volume'].map(s=><th key={s} scope="col" className="p-2 font-medium">{s}</th>)}</tr></thead><tbody>{bars.map(bar=><tr key={bar.timestamp} className="border-t border-border"><td className="p-2">{bar.date}</td><td className="p-2">{money(bar.close)}</td><td className="p-2">{compact(bar.volume)}</td></tr>)}</tbody></table></div></details></>}
  </section>;
}
export default StockChart;
